spring.datasource.url=jdbc:mysql://localhost:3306/parqueadero_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.data.mongodb.uri=mongodb+srv://alejandraarboleda053_db_user:Parqueadero123@cluster0.6h0obon.mongodb.net/parqueaderos?retryWrites=true&w=majority&appName=Cluster0


jwt.secret=mi_clave_super_segura_12345678901234567890

